### ISSUE TITLE
Fail to load aiState from saved game: 'set' object has no attribute 'keys'

### ISSUE THREAD

**Issue by agrrr3** [Dilvish-fo/freeorion#12]
hi,

the imperial-stockpile branch does not seem to save/load correctly.
Saving "works", loading gives an error message and reloading crashes the game.

not sure if it is because of the branch or if it is in master (and maybe already fixed)

regards

**Comment by Morlic-fo** [comment]
This already has been fixed in master (d983db8703e377767ed80869e68c76cfbb50e707). The fix will only work for new savegames though.

**Comment by Dilvish-fo** [comment]
As the branch has been rebased to current master, I think this should be resolved now.
